import axios from "axios";
import "dotenv/config";
import { basePrompt } from "../utils/promptTemplate.js";

// export const generateDescription = async (script) => {

//   try {

//     const response = await axios.post(
//       "https://api.ai21.com/studio/v1/chat/completions",
//       {
//         model: "jamba-Large",
//         messages: [
//           {
//             role: "user",
//             content: basePrompt("description",script)
//           }
//         ]
//       },
//       {
//         headers: {
//           // Authorization: `Bearer ${process.env.AI21_API_KEY}`,
//           Authorization: `Bearer 9b549d47-2fd1-42b2-bf2a-4746adab2c8e`,
//           "Content-Type": "application/json"
//         }
//       }
//     );

//     return response.data.choices[0].message.content;

//   } catch (error) {

//     console.error(
//       "❌ AI21 Error:",
//       error.response?.data || error.message
//     );

//     return {
//       provider: "AI21",
//       error: true,
//       message: error.message
//     };

//   }

// };


import { CohereClientV2 } from "cohere-ai";

const cohere = new CohereClientV2({
  token: process.env.COHERE_API_KEY,
});

export const generateDescription = async (script) => {
  try {
    const response = await cohere.chat({
      model: "command-a-plus-05-2026",
      messages: [
        {
          role: "user",
          content: basePrompt("description", script),
        },
      ],
    });

    // Debug (optional)
    // console.log("📌 Full Cohere Response:");
    // console.dir(response.message.content, { depth: null });

    // Sirf text block nikaalo
    const description = response.message.content
      ?.filter((item) => item.type === "text")
      ?.map((item) => item.text)
      ?.join("\n")
      ?.trim();

    if (!description) {
      throw new Error("No description generated by Cohere.");
    }

    // console.log("✅ Description:");
    // console.log(description);

    return description;

  } catch (error) {
    console.error(
      "❌ Cohere Error:",
      error.body || error.message || error
    );

    return {
      provider: "Cohere",
      error: true,
      message: error.message,
    };
  }
};