import Cerebras from "@cerebras/cerebras_cloud_sdk";
import "dotenv/config";
import { basePrompt } from "../utils/promptTemplate.js";

const cerebras = new Cerebras({
  apiKey: process.env.CEREBRAS_API_KEY,
});

const CLOUDFLARE_MODEL = "@cf/zai-org/glm-4.7-flash";

export async function generateWithCloudflare(topic) {
  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/ai/run/${CLOUDFLARE_MODEL}`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.CLOUDFLARE_API_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messages: [
          {
            role: "user",
            content: basePrompt("hashtags", topic),
          },
        ],
      }),
    }
  );

  const result = await response.json();

  if (!response.ok || !result.success) {
    throw new Error(
      result.errors?.map((err) => err.message).join(", ") ||
        `Cloudflare API error: ${response.status}`
    );
  }
// console.log(result.result.choices[0].message.content);
  return result.result.choices[0].message.content;
}

export async function generateHashtags(topic) {
  // 1️⃣ First try Cerebras
  try {
    console.log("🤖 Trying Cerebras...");

    const response = await cerebras.chat.completions.create({
      model: "gpt-oss-120b",
      messages: [
        {
          role: "user",
          content: basePrompt("hashtags", topic),
        },
      ],
    });

    // console.log("✅ Hashtags generated by Cerebras");

    return response.choices[0].message.content;

  } catch (cerebrasError) {

    // console.error(
    //   "❌ Cerebras failed:",
    //   cerebrasError.message
    // );

    // 2️⃣ Fallback to Cloudflare
    try {
      console.log("🔄 Switching to Cloudflare AI...");

      const result = await generateWithCloudflare(topic);

      // console.log("✅ Hashtags generated by Cloudflare");

      return result;

    } catch (cloudflareError) {

      console.error(
        "❌ Cloudflare also failed:",
        cloudflareError.message
      );

      return {
        provider: "Cerebras + Cloudflare",
        error: true,
        message: "Both AI providers failed",
        details: {
          cerebras: cerebrasError.message,
          cloudflare: cloudflareError.message,
        },
      };
    }
  }
}